import type { Project } from "@/types/entities";

export const projects: Project[] = [
  {
    id: "green-shop",
    title: "Green Shop Brand",
    subtitle: "Интернет-магазин натуральной продукции",
    description:
      "Каталог с поиском и фильтрами, корзина, избранное, сравнение товаров, NextAuth, личный кабинет, заказы в Firestore, тёмная тема, Storybook и тесты. Jest + React Testing Library: тесты ключевых компонентов. Storybook: визуальная документация 12+ компонентов UI-кита. Тёмная тема через styled-components.",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "styled-components",
      "Redux Toolkit",
      "RTK Query",
      "Firebase",
      "NextAuth",
      "Storybook",
      "React Testing Library",
      "Jest",
      "ESLint",
      "Prettier",
    ],
    kind: "pet",
    githubUrl: "https://github.com/rmxway/green-shop",
    demoUrl: "https://green-shop-brand.vercel.app/",
    accent: "emerald",
    previewImage: "/img/green-shop.jpg",
  },
  {
    id: "medanketa",
    title: "Medanketa",
    subtitle: "Медицинские анкеты и аналитика",
    description:
      "Список и прохождение анкет, статистика, шаблоны и справочники. Интеграция API, оптимизация загрузки и рефакторинг.",
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "TanStack Query",
      "styled-components",
      "ESLint",
      "Prettier",
    ],
    kind: "commercial",
    githubUrl: "https://github.com/rmxway/medanketa",
    demoUrl: "https://medanketa.com/",
    accent: "purple",
    previewImage: "/img/medanketa.jpg",
  },
  {
    id: "stories",
    title: "Stories",
    subtitle: "Виджет историй в духе мессенджеров и соцсетей",
    description:
      "Демо виджета историй в стиле соцсетей: превью с кольцом прогресса, полноэкранный просмотр с автопереключением, навигация по тапам и клавиатуре, двухпальцевый zoom активной истории, режим просмотра зрителей и запоминание просмотренных в localStorage. Настроил ESLint/Prettier, написал README с инструкцией по запуску — код готов к передаче в команду.",
    stack: [
      "Next.js",
      "TypeScript",
      "styled-components",
      "Framer Motion",
      "ESLint",
      "Prettier",
    ],
    kind: "pet",
    githubUrl: "https://github.com/rmxway/stories",
    demoUrl: "https://stories-widget.vercel.app/",
    accent: "violet",
    previewImage: "/img/stories.jpg",
  },
  {
    id: "simpletrading",
    title: "Simple Trading",
    subtitle: "USD, EUR, CNY к рублю по данным ЦБ РФ",
    description:
      "Трекер курсов доллара, евро и юаня к рублю: график за три месяца, переключение валюты, живые данные ЦБ. Интерфейс не моргает при смене котировки — старые цифры остаются, пока грузятся новые. Если запрос упал, значения не пропадают, а ошибка всплывает уведомлением. Архитектура FSD для лёгкой поддержки.",
    stack: [
      "Next.js",
      "TypeScript",
      "TanStack Query",
      "styled-components",
      "MUI",
      "lightweight-charts",
      "Framer Motion",
      "ESLint",
      "Prettier",
    ],
    kind: "pet",
    githubUrl: "https://github.com/rmxway/simpletrading",
    demoUrl: "https://simpletrading-page.vercel.app/",
    accent: "yellow",
    previewImage: "/img/simpletrading.jpg",
  },
  {
    id: "react-notes",
    title: "React Notes",
    subtitle: "Заметки и задачи на FSD",
    description:
      "CRUD заметок, фильтры, сортировка, оптимистичные обновления React Query, NextAuth и Firestore. FSD-архитектура для масштабирования.",
    stack: [
      "Next.js 14",
      "TypeScript",
      "FSD",
      "styled-components",
      "Redux Toolkit",
      "TanStack Query",
      "NextAuth",
      "Vitest",
      "Framer Motion",
      "ESLint",
      "Prettier",
    ],
    kind: "pet",
    githubUrl: "https://github.com/rmxway/react-notes",
    demoUrl: "https://react-notes-service.vercel.app",
    accent: "indigo",
    previewImage: "/img/notes.jpg",
  },
  {
    id: "itguru-test",
    title: "Products table",
    subtitle: "Тестовое задание от itGuru",
    description:
      "Авторизация DummyJSON, таблица товаров с пагинацией, поиск, сортировка, оптимистичное добавление в кэш React Query. React Hook Form + Yup: валидация форм с обработкой ошибок и состояний загрузки",
    info: "login: emilys, password: emilyspass",
    stack: [
      "React 19",
      "TypeScript",
      "Vite 7",
      "TanStack Query",
      "axios",
      "React Hook Form",
      "Yup",
    ],
    kind: "test",
    githubUrl: "https://github.com/rmxway/itguru-test",
    demoUrl: "https://rmxway.github.io/itguru-test/",
    accent: "sky",
    previewImage: "/img/itguru.jpg",
  },
  {
    id: "sokolinayaohota",
    title: "Соколиная охота",
    subtitle: "Сайт ресторана",
    description:
      "Вариант сайта ресторана на Next.js. Главная страница в виде лендинга, галерея, залы с описанием и бронированием, контакты.",
    stack: [
      "Next.js 16",
      "React 19",
      "styled-components",
      "Framer Motion",
      "Storybook",
      "Docker",
      "Prettier",
    ],
    kind: "commercial",
    githubUrl: "https://github.com/rmxway/sokolinayaohota",
    demoUrl: "https://sokolinayaohota.vercel.app/",
    accent: "amber",
    previewImage: "/img/sokol.jpg",
  },
  {
    id: "askona",
    title: "Askona",
    subtitle: "Аскона Тех — разработка и поддержка сайта",
    description:
      "Каталог, фильтры, карточка товара, подборщики, UI Kit, менторинг фронтенда, Agile/Scrum и ускорение загрузки страниц.",
    stack: ["React", "TypeScript", "UI Kit", "Адаптивная вёрстка"],
    kind: "commercial",
    demoUrl: "https://www.askona.ru/",
    accent: "cyan",
    previewImage: "/img/askona.jpg",
  },
  {
    id: "zoloto585",
    title: "Золото 585",
    subtitle: "Холдинг 585 — ювелирный ритейл",
    description:
      "От вёрстки до React: формы с валидацией, каталоги, карточки товаров, рефакторинг и оптимизация скорости загрузки.",
    stack: ["React", "Webpack", "SCSS", "Формы и валидация"],
    kind: "commercial",
    demoUrl: "https://zoloto585.ru/",
    accent: "yellow",
    previewImage: "/img/gold.jpg",
  },
];
